"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = [('', ['data'])]
OPTIONS = {
    'iconfile':'data/images/Sack_Run_icon.PNG'
}

setup(
    app=APP,
    py_modules=['bear_trap_class', 'bee', 'button', 'display_fps', 'eq_management', 'font_manager', 'game', 'image_loader',
                'level_transition', 'levels', 'main', 'menu', 'particles', 'pause_screen', 'plant_spit', 'player',
                'popup_bg_generator', 'screen_info', 'scroll_bar', 'settings', 'shockwave', 'world', 'world_selection'],
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
